export enum BodyworkType {
    DOES_NOT_APPLY = 'VEHICLE.BODYWORK_TYPE.DOES_NOT_APPLY',
    STAKE_BODY = 'VEHICLE.BODYWORK_TYPE.STAKE_BODY',
    VAN = 'VEHICLE.BODYWORK_TYPE.VAN',
    REFRIGERATED_VAN = 'VEHICLE.BODYWORK_TYPE.REFRIGERATED_VAN',
    TANK = 'VEHICLE.BODYWORK_TYPE.TANK',
    HOPPER = 'VEHICLE.BODYWORK_TYPE.HOPPER',
    IRON = 'VEHICLE.BODYWORK_TYPE.IRON',
    CONTAINER_SHIP = 'VEHICLE.BODYWORK_TYPE.CONTAINER_SHIP',
    NURSE = 'VEHICLE.BODYWORK_TYPE.NURSE',
}
