export enum Weekday {
    MONDAY = 'WEEKDAY.MONDAY',
    TUESDAY = 'WEEKDAY.TUESDAY',
    WEDNESDAY = 'WEEKDAY.WEDNESDAY',
    THURSDAY = 'WEEKDAY.THURSDAY',
    FRIDAY = 'WEEKDAY.FRIDAY',
    SATURDAY = 'WEEKDAY.SATURDAY',
    SUNDAY = 'WEEKDAY.SUNDAY',
}
