export enum VehicleFile {
    CUSTOM = 'FILE.TYPE.CUSTOM',
    OWNERSHIP_CARD = 'FILE.TYPE.OWNERSHIP_CARD',
    SOAT = 'FILE.TYPE.SOAT',
    TECNOMECANICA = 'FILE.TYPE.TECNOMECANICA',
    INSURANCE = 'FILE.TYPE.INSURANCE',
}

export enum DriverFile {
    CUSTOM = 'FILE.TYPE.CUSTOM',
    ID = 'FILE.TYPE.ID',
    LICENSE = 'FILE.TYPE.LICENSE',
    SOCIAL_SECURITY = 'FILE.TYPE.SOCIAL_SECURITY',
}
