export enum LoadType {
    CONTENTED_20 = 'LOAD.TYPE.CONTENTED_20',
    CONTENTED_40 = 'LOAD.TYPE.CONTENTED_40',
    BULK = 'LOAD.TYPE.BULK',
    PALLETIZED = 'LOAD.TYPE.PALLETIZED',
    DRIES = 'LOAD.TYPE.DRIES',
    PIPELINE = 'LOAD.TYPE.PIPELINE',
    LIQUID = 'LOAD.TYPE.LIQUID',
}
