export enum Module {
    PUBLICATION = 'CUSTOM_FIELD.MODULE.PUBLICATION',
    VEHICLE_REPORT = 'CUSTOM_FIELD.MODULE.VEHICLE_REPORT',
    TRIP_REPORT = 'CUSTOM_FIELD.MODULE.TRIP_REPORT',
    YARD_CONTROL = 'CUSTOM_FIELD.MODULE.YARD_CONTROL',
}
