export enum TripReport {
    NOT_STARTED = 'STATE.NOT_STARTED',
    AT_ORIGIN = 'STATE.AT_ORIGIN',
    WAITING_LOAD = 'STATE.WAITING_LOAD',
    LOADED = 'STATE.LOADED',
    ON_ROUTE_TO_ORIGIN = 'STATE.ON_ROUTE_TO_ORIGIN',
    ON_ROUTE_TO_DESTINY = 'STATE.ON_ROUTE_TO_DESTINY',
    AT_DESTINY = 'STATE.AT_DESTINY',
    UNLOADING = 'STATE.UNLOADING',
    COMPLETED = 'STATE.COMPLETED',
    CANCELLED = 'STATE.CANCELLED',
}
