export enum VehicleType {
    TURBOCHARGE = 'VEHICLE.TYPE.TURBOCHARGE', // Turbo
    SIMPLE = 'VEHICLE.TYPE.SIMPLE', // Sencillo
    FOUR_WHEEL_DRIVE = 'VEHICLE.TYPE.FOUR_WHEEL_DRIVE', //Doble troque
    TRUNKING_RIG_MINI = 'VEHICLE.TYPE.TRUNKING_RIG_MINI', // Mini mula
    TRUNKING_RIG = 'VEHICLE.TYPE.TRUNKING_RIG', // Tracto mula
    LOW_BOY_TRUCK = 'VEHICLE.TYPE.LOW_BOY_TRUCK', // Cama baja
}
